SELECT
  TASK_NAME,
  UPET.STATUS TASK_STATUS,
  UPET.TABLE_OWNER CHUNKED_TABLE_OWNER,
  UPET.TABLE_NAME CHUNKED_TABLE_NAME,
  TO_CHAR (START_TS, 'DD-MON-RR HH24:MI:SS') START_TS,
  TO_CHAR (END_TS, 'DD-MON-RR HH24:MI:SS') END_TS,
  CASE UPET.STATUS
    WHEN 'FINISHED' THEN END_TS - START_TS
    ELSE NULL
  END RUN_DURATION,
  CASE UPET.STATUS
    WHEN 'FINISHED' THEN NULL
    ELSE CURRENT_TIMESTAMP - START_TS
  END ELAPSED,
  ROUND (((A.PROCESSED+A.PROCESSED_WITH_ERROR) / (A.ASSIGNED + A.PROCESSED + A.UNASSIGNED + A.PROCESSED_WITH_ERROR)) * 100, 2) PCT_COMPLETE,
  A.ASSIGNED + A.PROCESSED + A.UNASSIGNED + A.PROCESSED_WITH_ERROR TOTAL_CHUNKS,
  A.PROCESSED,
  A.ASSIGNED,
  A.UNASSIGNED,
  A.PROCESSED_WITH_ERROR
FROM
(  
  SELECT
    TASK_NAME,
    MIN (START_TS) START_TS,
    MAX (END_TS) END_TS,
    SUM (NVL (ASSIGNED, 0)) ASSIGNED,
    SUM (NVL (PROCESSED, 0)) PROCESSED,
    SUM (NVL (UNASSIGNED, 0)) UNASSIGNED,
    SUM (NVL (PROCESSED_WITH_ERROR, 0)) PROCESSED_WITH_ERROR
  FROM
  (
    SELECT
      UPEC.TASK_NAME,
      UPEC.STATUS,
      COUNT (1) CHUNK_COUNT,
      NVL (MIN (USJRD.ACTUAL_START_DATE), CURRENT_TIMESTAMP - MIN (USRJ.ELAPSED_TIME)) START_TS,
      MAX (USJRD.ACTUAL_START_DATE + USJRD.RUN_DURATION) END_TS
    FROM USER_PARALLEL_EXECUTE_CHUNKS UPEC
    LEFT JOIN USER_SCHEDULER_JOB_RUN_DETAILS USJRD
      USING (JOB_NAME)
    LEFT JOIN USER_SCHEDULER_RUNNING_JOBS USRJ
      USING (JOB_NAME)
    GROUP BY
      UPEC.TASK_NAME,
      UPEC.STATUS
  )
  PIVOT
  (
    SUM (CHUNK_COUNT)
    FOR STATUS IN
    (
      'UNASSIGNED' AS UNASSIGNED,
      'PROCESSED' AS PROCESSED,
      'ASSIGNED' AS ASSIGNED,
      'PROCESSED_WITH_ERROR' AS PROCESSED_WITH_ERROR
    )
  )
  GROUP BY TASK_NAME
) A
JOIN USER_PARALLEL_EXECUTE_TASKS UPET
  USING (TASK_NAME)
ORDER BY
  CASE UPET.STATUS
    WHEN 'PROCESSING' THEN '1'
    ELSE UPET.STATUS
  END
;







